# basic options
title: Rushali Kothari
author: GitHub User
email: rkothari31@yahoo.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

Lorem ipsum dolor sit amet, mei at eruditi laboramus assentior, nec no nisl semper reprehendunt. 
Sonet solet propriae quo te, ea usu affert omnium deseruisse, ne mundi prompta copiosae duo. 
Sed an movet consequuntur, ad sed mazim alterum equidem. Dicta scripta vituperata per ea, vix quem integre persecuti cu.

# Build settings
markdown: kramdown
theme: minima
